id: nbs
data_pack:
  name: nbs-smithed-summit-24
  description: "Data pack for NBS on the Smithed Summit 2024"
  load: [src]
resource_pack:
  name: nbs-smithed-summit-24
  description: "Resource pack for NBS on the Smithed Summit 2024"
  load: [assets]
pipeline:
  - pigstep
  - nbs.music
  - beet.contrib.scoreboard