id: nbs-panel

data_pack:
  name: nbs-panel-24-dp
  description: "Data pack for the NBS panel on Smithed Summit 2024"
  load:
    - data/nbs/module: src/panel
  # zipped: true

resource_pack:
  name: nbs-panel-24-rp
  description: "Resource pack for the NBS panel on Smithed Summit 2024"
  load: [assets]
  # zipped: true

require: [bolt]
pipeline:
  - mecha
  - src.sound_config
  - src.panel.panel

output: dist/panel

meta:
  bolt:
    entrypoint: "*"
