id: nbs

data_pack:
  name: nbs-smithed-summit-24
  description: "Data pack for NBS on the Smithed Summit 2024"
  load:
    - data/nbs/module: src
    - data: src/data
  zipped: true

resource_pack:
  name: nbs-smithed-summit-24
  description: "Resource pack for NBS on the Smithed Summit 2024"
  load: [assets]
  zipped: true

require: [bolt]
pipeline:
  - nbs.model
  - mecha

output: dist

meta:
  bolt:
    entrypoint: "*"
