[tool.poetry]
name = "nbs-smithed-summit-24"
version = "0.1.0"
description = "Note Block Studio data pack + resource pack for Smithed Summit 2024"
authors = ["Bentroen <bemcdc@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
beet = {extras = ["image"], version = "^0.108.5"}
pynbs = "^1.1.0"
bolt = "^0.49.1"

[tool.poetry.group.dev.dependencies]
snakeviz = "^2.2.0"
tuna = "^0.5.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
