# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.music_speaker.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'music_speaker', 'function_path': 'animated_java:music_speaker/animations/animation_speaker_beat_4/play'}
tag @s add aj.music_speaker.animation.animation_speaker_beat_4.playing
scoreboard players set @s aj.animation_speaker_beat_4.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:music_speaker/animations/animation_speaker_beat_4/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only