# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.music_speaker.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'music_speaker', 'function_path': 'animated_java:music_speaker/animations/animation_speaker_beat_1/next_frame'}
execute if score @s aj.animation_speaker_beat_1.frame matches 9.. run scoreboard players set @s aj.animation_speaker_beat_1.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.animation_speaker_beat_1.frame
execute at @s run function animated_java:music_speaker/animations/animation_speaker_beat_1/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.animation_speaker_beat_1.frame 1