# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.music_speaker.bone.antenna] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_antenna set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.music_speaker.bone.speaker_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_speaker_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.music_speaker.bone.speaker_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_speaker_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.music_speaker.bone.text_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.text_display_text_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.music_speaker.bone.details] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_details set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.music_speaker.bone.stereo] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_stereo set from storage aj:uuid main.out