# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:music_speaker/animations/animation_speaker_playing_120/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.animation_speaker_playing_120.frame 1