# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.music_speaker.root] run return 0
execute on passengers if entity @s[tag=aj.music_speaker.data] unless data entity @s {data:{rigHash: '161acab26de4cba90bedfd171f5231a5a315b02ec9aef87b4b4f73d03abc5813'}} on vehicle run function animated_java:music_speaker/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1