# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.music_speaker.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:music_speaker/as_root/pre_tick
execute if entity @s[tag=aj.music_speaker.animation.animation_speaker_playing_120.playing] run function animated_java:music_speaker/animations/animation_speaker_playing_120/zzz/on_tick
execute if entity @s[tag=aj.music_speaker.animation.animation_speaker_beat_1.playing] run function animated_java:music_speaker/animations/animation_speaker_beat_1/zzz/on_tick
execute if entity @s[tag=aj.music_speaker.animation.animation_speaker_beat_2.playing] run function animated_java:music_speaker/animations/animation_speaker_beat_2/zzz/on_tick
execute if entity @s[tag=aj.music_speaker.animation.animation_speaker_beat_3.playing] run function animated_java:music_speaker/animations/animation_speaker_beat_3/zzz/on_tick
execute if entity @s[tag=aj.music_speaker.animation.animation_speaker_beat_4.playing] run function animated_java:music_speaker/animations/animation_speaker_beat_4/zzz/on_tick
execute on passengers if entity @s[tag=aj.music_speaker.data] run function animated_java:music_speaker/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:music_speaker/as_root/post_tick